name: 'Client: Test'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'cli/**'
  pull_request:
    branches:
    - main
    paths:
    - 'cli/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [15.x, 14.x, 12.x, 10.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: |
        yarn install --frozen-lockfile
        yarn test
      working-directory: ./src
