name: 'Client: Release'

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - run: |
        yarn install --frozen-lockfile
        yarn publish
      working-directory: ./src
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://npm.pkg.github.com/
        scope: '@fluteds'
    - run: |
        yarn install --frozen-lockfile
        yarn publish
      working-directory: ./src
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
